#!/usr/bin/env python3
"""
Generate token-prediction NLA descriptions for Phi-4 via Azure GPT-4o.

V2 of the description corpus ("trash in, trash out" fix, 2026-06-11):
the prompt demands the CONCRETE continuation being prepared at the given
depth — actual tokens/phrases/entities, plain prose, zero scaffold
(no "imperative verb as directive head", no meta-notes, no bullets).

Unsafe categories (F35, F36, I44, L59) are excluded at load time and never
touched — when the safe dataset works, the remainder gets generated by a
local adapted model with few-shot examples from the healthy data.

Layer set: the 7 demo layers (4,10,16,20,26,32,38 of 40). Full 13-band
coverage only after the recipe is proven.

Usage:
  export AI_KEY=$(az cognitiveservices account keys list --name anna52-ai \
      --resource-group anna52-ai-rg --query "key1" -o tsv)
  python3 scripts/generate_descriptions_phi4_azure.py --test 8
  python3 scripts/generate_descriptions_phi4_azure.py            # full run
"""
import json, os, argparse, time, sys, random, urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
GENERATED_DIR = REPO_ROOT / "corpus" / "generated"

ENDPOINT = os.environ.get("AI_ENDPOINT", "https://eastus.api.cognitive.microsoft.com")
API_KEY = os.environ.get("AI_KEY", "")

UNSAFE_PREFIXES = ("F35", "F36", "I44", "L59")
N_LAYERS = 40
DEFAULT_LAYERS = "4,10,16,20,26,32,38"

GROUND_LAYERS = {32, 38}

BAND_OF = {4: "early", 10: "early", 16: "mid", 20: "mid", 26: "mid",
           32: "late", 38: "late"}

EXAMPLES = {
    "early": 'Dernier jour d\'un condamné, Antigone, Boîte à merveilles — '
             'surface repetition of the exam-novel sequence; echoes of '
             '\'predict\' and \'2023\' with rephrasings of the year list.',
    "mid": 'A direct link to Microsoft\'s official Windows 10 ISO download '
           'page plus brief edition and language instructions; the ask for '
           'an \'official iso direct link\' selects the authoritative '
           'source.',
    "late": 'The literal opening «The preterite form of \'jump\' is '
            '\'jumped\'.» — committed tokens completing the grammar answer; '
            'the bare question selects the direct form.',
}

GROUNDING_BLOCK = """
The model's ACTUAL reply to this text begins (greedy decoding):
«{reply_prefix}»
Describe the near-final prediction state consistent with this real opening — quote its first tokens.
"""

PROMPT_TEMPLATE = """A language model (Phi-4, 40 layers) has read the text below and is about to respond. We are looking at its internal state at layer {layer} of 40 ({depth_pct}% depth).{layer_hint}

In 2-3 plain sentences (~70 words total), give the content of the prediction AT THIS DEPTH: the concrete tokens, phrases or material coming next, plus what in the text selects it. Write the description AS the content itself, never as commentary about the model or the continuation: forbidden openers and frames include "The continuation will", "It will mention", "is being prepared", "the model", "the response". Use the text's actual entities, numbers and names — never grammatical labels. Definite claims only — no "likely/may/might/could". No bullets, headers, or notes about these instructions.

Example of the required style (for a different text at a similar depth):
{example}
{grounding}
TEXT:
{text}"""

LAYER_HINTS = {
    4: " At 10% depth only token identity and local syntax are resolved;"
       " describe surface-level continuations — echoes and rephrasings of"
       " the text's own salient terms, not themes or plans.",
    10: " At 25% depth phrase structure and entities are bound; the topic is"
        " identified but the response is not yet planned.",
    16: " At 40% depth the task and intent are recognized; candidate"
        " response types compete.",
    20: " At 50% depth response planning begins; specific content for the"
        " reply is being assembled.",
    26: " At 65% depth the response strategy is committed; the model holds"
        " the specific facts, items or lines it will produce.",
    32: " At 80% depth the wording and ordering of the upcoming output are"
        " being fixed.",
    38: " At 95% depth the model is committed to near-final tokens — the"
        " literal opening of its reply.",
}


def call_gpt4o(prompt, max_retries=5):
    for attempt in range(max_retries):
        try:
            url = f"{ENDPOINT}/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21"
            body = json.dumps({
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 220, "temperature": 0.3,
            }).encode()
            req = urllib.request.Request(url, data=body, headers={
                "Content-Type": "application/json", "api-key": API_KEY,
            })
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = json.load(resp)
            return data["choices"][0]["message"]["content"].strip()
        except urllib.error.HTTPError as e:
            if e.code == 429:
                wait = 2 ** attempt * 5
                print(f"    Rate limited, waiting {wait}s...", file=sys.stderr)
                time.sleep(wait)
            elif e.code == 400:
                return None  # content filter — skip, never retry
            elif attempt < max_retries - 1:
                time.sleep(2 ** attempt)
            else:
                print(f"    Error: {e}", file=sys.stderr)
                return None
        except Exception as e:
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)
            else:
                print(f"    Error: {e}", file=sys.stderr)
                return None
    return None


META_OPENERS = ("the continuation", "it will", "the model", "the response",
                "the reply", "the output")

RETRY_NOTE = ("\n\nYour previous answer opened with forbidden meta framing. "
              "Rewrite: state the content directly, starting with the "
              "concrete material itself.")


def is_meta(desc):
    return desc is None or len(desc) < 15 or \
        desc.lower().lstrip('"“ ').startswith(META_OPENERS)


def build_prompt(item, L, ground_map):
    pct = round(L / N_LAYERS * 100)
    grounding = ""
    if L in GROUND_LAYERS and ground_map and item["id"] in ground_map:
        grounding = GROUNDING_BLOCK.format(
            reply_prefix=ground_map[item["id"]][:300])
    return PROMPT_TEMPLATE.format(
        layer=L, depth_pct=pct, layer_hint=LAYER_HINTS.get(L, ""),
        example=EXAMPLES[BAND_OF.get(L, "mid")], grounding=grounding,
        text=item["text"][:2000])


def is_safe(item):
    cat = str(item.get("category", "")) + str(item.get("id", ""))
    return not any(cat.startswith(p) or p in cat[:6] for p in UNSAFE_PREFIXES)


def load_texts():
    texts, seen = [], set()
    for path in sorted(GENERATED_DIR.glob("[A-Z]*.json")):
        if any(path.name.startswith(p) for p in UNSAFE_PREFIXES):
            continue
        for item in json.loads(path.read_text()):
            if ("text" in item and item.get("id") not in seen
                    and len(item["text"]) > 20 and is_safe(item)):
                seen.add(item["id"])
                texts.append(item)
    for name in ["expansion_texts.json", "wildchat_stratified.json"]:
        path = GENERATED_DIR / name
        if path.exists():
            for item in json.loads(path.read_text()):
                if ("text" in item and item.get("id") not in seen
                        and len(item["text"]) > 20 and is_safe(item)):
                    seen.add(item["id"])
                    texts.append(item)
    return texts


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--test", type=int, default=0)
    parser.add_argument("--layers", default=DEFAULT_LAYERS)
    parser.add_argument("--output",
                        default="corpus/generated/descriptions_phi4_tokenpred_gpt4o.json")
    parser.add_argument("--max-texts", type=int, default=0,
                        help="cap text count (pilot); 0 = all safe texts")
    parser.add_argument("--checkpoint-every", type=int, default=20)
    parser.add_argument("--delay", type=float, default=0.3)
    parser.add_argument("--ground-file", default="",
                        help="JSON {id: actual_reply_prefix} for GROUND_LAYERS")
    parser.add_argument("--texts-file", default="",
                        help="use this JSON list of texts instead of the full corpus")
    args = parser.parse_args()

    if not API_KEY:
        print("Set AI_KEY env var first.", file=sys.stderr)
        sys.exit(1)

    layers = [int(x) for x in args.layers.split(",")]
    output_path = REPO_ROOT / args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if args.texts_file:
        texts = [t for t in json.loads(Path(args.texts_file).read_text())
                 if is_safe(t)]
    else:
        texts = load_texts()
    if args.max_texts:
        rng = random.Random(42)
        texts = rng.sample(texts, min(args.max_texts, len(texts)))
    ground_map = (json.loads(Path(args.ground_file).read_text())
                  if args.ground_file else {})
    print(f"Safe texts: {len(texts)}  layers: {layers}  "
          f"calls needed: {len(texts) * len(layers)}")

    if args.test:
        rng = random.Random(7)
        sample = rng.sample(texts, args.test)
        for item in sample:
            L = rng.choice(layers)
            out = call_gpt4o(build_prompt(item, L, ground_map))
            print(f"\n=== {item['id']} ({item.get('category','?')}) L{L} "
                  f"({round(L / N_LAYERS * 100)}%) ===")
            print(f"TEXT: {item['text'][:160]}...")
            print(f"DESC: {out}")
        return

    existing = json.loads(output_path.read_text()) if output_path.exists() else []
    done = {(d["id"], d["layer"]) for d in existing}
    descs = list(existing)
    n_ok = n_fail = 0
    t0 = time.time()
    for item in texts:
        for L in layers:
            if (item["id"], L) in done:
                continue
            pct = round(L / N_LAYERS * 100)
            out = call_gpt4o(build_prompt(item, L, ground_map))
            if out and is_meta(out):
                retry = call_gpt4o(build_prompt(item, L, ground_map) + RETRY_NOTE)
                if retry and not is_meta(retry):
                    out = retry
            if out:
                rec = {"id": item["id"], "layer": L, "depth_pct": pct,
                       "category": item.get("category"),
                       "group": item.get("group"),
                       "description": out}
                if L in GROUND_LAYERS and item["id"] in ground_map:
                    rec["grounded"] = True
                    rec["reply_prefix"] = ground_map[item["id"]][:300]
                descs.append(rec)
                n_ok += 1
            else:
                n_fail += 1
            if (n_ok + n_fail) % args.checkpoint_every == 0:
                output_path.write_text(json.dumps(descs, indent=1))
                rate = (n_ok + n_fail) / max(time.time() - t0, 1)
                print(f"  {n_ok} ok / {n_fail} fail  ({rate:.1f}/s)", flush=True)
            time.sleep(args.delay)
    output_path.write_text(json.dumps(descs, indent=1))
    print(f"DONE: {n_ok} ok, {n_fail} failed -> {output_path}")


if __name__ == "__main__":
    main()
